INFO 2022-04-15 07:41:40,580 autoreload 7388 140617116010304 Watching for file changes with StatReloader
INFO 2022-04-15 07:45:04,989 autoreload 7696 139667684927296 Watching for file changes with StatReloader
INFO 2022-04-15 07:50:51,939 autoreload 8474 139813329745728 Watching for file changes with StatReloader
INFO 2022-04-15 07:51:21,601 autoreload 8474 139813329745728 /home/tracy/tracy_git_test/meiduo_mall/meiduo_mall/settings.py changed, reloading.
INFO 2022-04-15 07:51:23,449 autoreload 8533 140020816381760 Watching for file changes with StatReloader
INFO 2022-04-15 07:53:16,273 autoreload 8806 139718955517760 Watching for file changes with StatReloader
INFO 2022-04-15 07:57:13,061 autoreload 8938 139933953828672 Watching for file changes with StatReloader
INFO 2022-04-15 07:57:17,846 basehttp 8938 139933895456512 "GET / HTTP/1.1" 200 10697
INFO 2022-04-15 09:05:22,222 autoreload 9485 140087987656512 Watching for file changes with StatReloader
INFO 2022-04-15 09:09:09,208 autoreload 9995 140113572312896 Watching for file changes with StatReloader
WARNING 2022-04-15 09:15:05,293 log 9995 140113261549312 Not Found: /username/tracy/count/
WARNING 2022-04-15 09:15:05,297 basehttp 9995 140113261549312 "GET /username/tracy/count/ HTTP/1.1" 404 2323
WARNING 2022-04-15 09:16:54,241 log 9995 140113261549312 Not Found: /
WARNING 2022-04-15 09:16:54,249 basehttp 9995 140113261549312 "GET / HTTP/1.1" 404 2242
INFO 2022-04-15 09:17:29,342 basehttp 9995 140113253156608 "GET /username/tracy/count HTTP/1.1" 200 39
INFO 2022-04-15 09:21:33,112 basehttp 9995 140113253156608 "GET /username/tracy/count HTTP/1.1" 200 39
WARNING 2022-04-15 09:24:39,337 log 9995 140113261549312 Not Found: /
WARNING 2022-04-15 09:24:39,343 basehttp 9995 140113261549312 "GET / HTTP/1.1" 404 2242
INFO 2022-04-16 05:20:53,845 autoreload 2701 139890878404416 Watching for file changes with StatReloader
WARNING 2022-04-16 05:21:39,497 log 2701 139890820032256 Not Found: /
WARNING 2022-04-16 05:21:39,500 basehttp 2701 139890820032256 "GET / HTTP/1.1" 404 2242
INFO 2022-04-16 05:22:24,755 basehttp 2701 139890820032256 "GET /admin HTTP/1.1" 301 0
INFO 2022-04-16 05:22:24,799 basehttp 2701 139890820032256 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-04-16 05:22:24,898 basehttp 2701 139890820032256 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2215
WARNING 2022-04-16 05:22:53,466 log 2701 139890820032256 Not Found: /username/tracy/count/
WARNING 2022-04-16 05:22:53,468 basehttp 2701 139890820032256 "GET /username/tracy/count/ HTTP/1.1" 404 2323
INFO 2022-04-16 05:23:18,767 basehttp 2701 139890820032256 "GET /username/abc/count HTTP/1.1" 200 39
WARNING 2022-04-16 05:23:29,511 log 2701 139890820032256 Not Found: /username/abc/count/
WARNING 2022-04-16 05:23:29,515 basehttp 2701 139890820032256 "GET /username/abc/count/ HTTP/1.1" 404 2317
INFO 2022-04-18 05:58:53,014 autoreload 4416 140586958014272 Watching for file changes with StatReloader
INFO 2022-04-18 05:59:08,325 autoreload 4416 140586958014272 /home/tracy/tracy_git_test/meiduo_mall/apps/user/urls.py changed, reloading.
INFO 2022-04-18 05:59:09,207 autoreload 4567 140191123760960 Watching for file changes with StatReloader
INFO 2022-04-18 05:59:21,609 autoreload 4677 140235527292736 Watching for file changes with StatReloader
WARNING 2022-04-18 05:59:38,572 log 4677 140235468658432 Not Found: /username/abc/count/
WARNING 2022-04-18 05:59:38,577 basehttp 4677 140235468658432 "GET /username/abc/count/ HTTP/1.1" 404 2323
WARNING 2022-04-18 06:00:18,093 log 4677 140235468658432 Not Found: /username/abcbfd/count/
WARNING 2022-04-18 06:00:18,096 basehttp 4677 140235468658432 "GET /username/abcbfd/count/ HTTP/1.1" 404 2332
INFO 2022-04-18 06:02:50,856 autoreload 4677 140235527292736 /home/tracy/tracy_git_test/meiduo_mall/apps/user/urls.py changed, reloading.
INFO 2022-04-18 06:02:51,459 autoreload 4745 140623033624384 Watching for file changes with StatReloader
INFO 2022-04-18 06:03:08,266 basehttp 4745 140622975252224 "GET /username/abcbfd/count/ HTTP/1.1" 200 39
INFO 2022-04-18 06:04:22,567 autoreload 4745 140623033624384 /home/tracy/tracy_git_test/meiduo_mall/apps/user/urls.py changed, reloading.
INFO 2022-04-18 06:04:23,124 autoreload 4786 140024636438336 Watching for file changes with StatReloader
INFO 2022-04-18 06:04:32,406 autoreload 4786 140024636438336 /home/tracy/tracy_git_test/meiduo_mall/apps/user/urls.py changed, reloading.
INFO 2022-04-18 06:04:32,764 autoreload 4798 140410387322688 Watching for file changes with StatReloader
INFO 2022-04-18 06:04:37,633 basehttp 4798 140410328950528 "GET /username/abcbfd/count/ HTTP/1.1" 200 39
WARNING 2022-04-18 06:05:21,296 log 4798 140410328950528 Not Found: /username/abcb/count/
WARNING 2022-04-18 06:05:21,299 basehttp 4798 140410328950528 "GET /username/abcb/count/ HTTP/1.1" 404 2326
INFO 2022-04-18 06:05:29,790 basehttp 4798 140410328950528 "GET /username/abc4b/count/ HTTP/1.1" 200 39
INFO 2022-04-18 06:06:55,127 autoreload 4798 140410387322688 /home/tracy/tracy_git_test/meiduo_mall/apps/user/urls.py changed, reloading.
INFO 2022-04-18 06:06:55,979 autoreload 4846 140332801955648 Watching for file changes with StatReloader
INFO 2022-04-18 06:14:55,067 autoreload 4846 140332801955648 /home/tracy/tracy_git_test/meiduo_mall/apps/user/urls.py changed, reloading.
INFO 2022-04-18 06:14:55,612 autoreload 4943 139881931470656 Watching for file changes with StatReloader
INFO 2022-04-18 06:15:17,037 autoreload 4943 139881931470656 /home/tracy/tracy_git_test/meiduo_mall/apps/user/urls.py changed, reloading.
INFO 2022-04-18 06:15:17,389 autoreload 4954 140281943136064 Watching for file changes with StatReloader
INFO 2022-04-18 06:17:01,366 autoreload 4954 140281943136064 /home/tracy/tracy_git_test/meiduo_mall/apps/user/urls.py changed, reloading.
INFO 2022-04-18 06:17:01,862 autoreload 5000 139903653787456 Watching for file changes with StatReloader
INFO 2022-04-18 06:21:09,737 autoreload 5000 139903653787456 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-18 06:21:10,236 autoreload 5141 140496229873472 Watching for file changes with StatReloader
INFO 2022-04-18 06:21:47,678 autoreload 5141 140496229873472 /home/tracy/tracy_git_test/meiduo_mall/apps/user/urls.py changed, reloading.
INFO 2022-04-18 06:21:48,164 autoreload 5169 139713897940800 Watching for file changes with StatReloader
INFO 2022-04-18 06:22:08,056 autoreload 5184 139987203450688 Watching for file changes with StatReloader
WARNING 2022-04-18 06:22:33,805 log 5184 139987077035776 Not Found: /mobile/13888888888/count/
WARNING 2022-04-18 06:22:33,809 basehttp 5184 139987077035776 "GET /mobile/13888888888/count/ HTTP/1.1" 404 2525
ERROR 2022-04-18 06:22:50,908 log 5184 139987077035776 Internal Server Error: /mobiles/13888888888/count/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'mobiles'
ERROR 2022-04-18 06:22:50,915 basehttp 5184 139987077035776 "GET /mobiles/13888888888/count/ HTTP/1.1" 500 70514
INFO 2022-04-18 06:24:30,109 autoreload 5344 140420453373760 Watching for file changes with StatReloader
INFO 2022-04-18 06:24:36,490 basehttp 5344 140420142589696 "GET /mobiles/13888888888/count/ HTTP/1.1" 200 39
WARNING 2022-04-18 06:24:48,119 log 5344 140420142589696 Not Found: /mobiles/1388888888/count/
WARNING 2022-04-18 06:24:48,125 basehttp 5344 140420142589696 "GET /mobiles/1388888888/count/ HTTP/1.1" 404 2525
INFO 2022-04-18 06:25:05,805 basehttp 5344 140420142589696 "GET /mobiles/13312345678/count/ HTTP/1.1" 200 39
INFO 2022-04-18 07:11:18,907 autoreload 6093 140078072145728 Watching for file changes with StatReloader
INFO 2022-04-18 07:16:02,725 autoreload 6093 140078072145728 /home/tracy/tracy_git_test/meiduo_mall/meiduo_mall/settings.py changed, reloading.
INFO 2022-04-18 07:16:04,985 autoreload 6219 139820751615808 Watching for file changes with StatReloader
ERROR 2022-04-18 07:17:49,529 log 6219 139820236846848 Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 32, in post
    body_base = request.bady()
AttributeError: 'WSGIRequest' object has no attribute 'bady'
ERROR 2022-04-18 07:17:49,536 basehttp 6219 139820236846848 "POST /user/ HTTP/1.1" 500 75015
INFO 2022-04-18 07:19:35,642 autoreload 6219 139820751615808 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-18 07:19:37,592 autoreload 6395 139702855878464 Watching for file changes with StatReloader
ERROR 2022-04-18 07:19:42,191 log 6395 139702679328512 Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 32, in post
    body_base = request.body()
TypeError: 'bytes' object is not callable
ERROR 2022-04-18 07:19:42,200 basehttp 6395 139702679328512 "POST /user/ HTTP/1.1" 500 74889
INFO 2022-04-18 07:24:16,006 autoreload 6631 140252715693888 Watching for file changes with StatReloader
ERROR 2022-04-18 07:24:19,693 log 6631 140252270642944 Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 34, in post
    body_json = body_str.loads()
AttributeError: 'str' object has no attribute 'loads'
ERROR 2022-04-18 07:24:19,702 basehttp 6631 140252270642944 "POST /user/ HTTP/1.1" 500 75840
INFO 2022-04-18 07:24:56,257 autoreload 6631 140252715693888 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-18 07:24:58,047 autoreload 6728 140548959876928 Watching for file changes with StatReloader
INFO 2022-04-18 07:25:03,038 basehttp 6728 140548509792000 "POST /user/ HTTP/1.1" 200 27
ERROR 2022-04-18 07:27:13,263 log 6728 140548509792000 Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'tracy01' for key 'tb_users.username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 67, in post
    User.objects.create_user(username=username,password=password,mobiles=mobile)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/contrib/auth/models.py", line 160, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/contrib/auth/models.py", line 154, in _create_user
    user.save(using=self._db)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'tracy01' for key 'tb_users.username'")
ERROR 2022-04-18 07:27:13,283 basehttp 6728 140548509792000 "POST /user/ HTTP/1.1" 500 200872
INFO 2022-04-18 07:28:13,619 basehttp 6728 140548509792000 "POST /user/ HTTP/1.1" 200 75
INFO 2022-04-18 07:39:27,289 autoreload 6728 140548959876928 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-18 07:39:29,087 autoreload 7020 140310236485440 Watching for file changes with StatReloader
INFO 2022-04-18 07:39:34,972 basehttp 7020 140309791471360 "POST /user/ HTTP/1.1" 200 75
INFO 2022-04-18 07:39:48,826 autoreload 7020 140310236485440 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-18 07:39:50,922 autoreload 7132 139784926299968 Watching for file changes with StatReloader
INFO 2022-04-18 07:40:36,343 basehttp 7132 139784475375360 "POST /user/ HTTP/1.1" 200 81
INFO 2022-04-18 07:40:53,798 basehttp 7132 139784475375360 "POST /user/ HTTP/1.1" 200 51
INFO 2022-04-18 08:01:49,578 autoreload 7132 139784926299968 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-18 08:01:51,450 autoreload 7469 140206004123456 Watching for file changes with StatReloader
INFO 2022-04-18 08:08:38,887 autoreload 7469 140206004123456 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-18 08:08:40,814 autoreload 8380 139836029171520 Watching for file changes with StatReloader
INFO 2022-04-18 08:08:53,434 basehttp 8380 139835584136960 "POST /user/ HTTP/1.1" 200 27
INFO 2022-04-18 08:40:42,958 autoreload 8380 139836029171520 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-18 08:40:45,499 autoreload 8819 139857866852160 Watching for file changes with StatReloader
INFO 2022-04-19 07:08:50,527 autoreload 12036 140130375558976 Watching for file changes with StatReloader
INFO 2022-04-19 07:13:43,705 autoreload 12219 140053780436800 Watching for file changes with StatReloader
INFO 2022-04-19 07:15:03,563 autoreload 12386 139899918583616 Watching for file changes with StatReloader
INFO 2022-04-19 07:18:25,332 autoreload 12564 140056179472192 Watching for file changes with StatReloader
INFO 2022-04-19 07:28:04,558 autoreload 12833 139880026560320 Watching for file changes with StatReloader
INFO 2022-04-19 07:32:49,904 autoreload 13033 139792716871488 Watching for file changes with StatReloader
INFO 2022-04-19 07:35:04,257 autoreload 13148 140277284640576 Watching for file changes with StatReloader
INFO 2022-04-19 07:39:21,338 autoreload 13445 140023372277568 Watching for file changes with StatReloader
INFO 2022-04-19 07:40:24,210 basehttp 13445 140022846060288 "POST /user/ HTTP/1.1" 200 27
INFO 2022-04-19 07:41:35,589 basehttp 13445 140022846060288 "POST /user/ HTTP/1.1" 200 27
INFO 2022-04-19 07:46:11,891 autoreload 14007 140702724953920 Watching for file changes with StatReloader
INFO 2022-04-19 07:54:28,730 autoreload 14221 140100161304384 Watching for file changes with StatReloader
INFO 2022-04-19 07:55:45,897 autoreload 14372 139943845877568 Watching for file changes with StatReloader
INFO 2022-04-19 07:56:06,303 autoreload 14508 139777605535552 Watching for file changes with StatReloader
INFO 2022-04-19 07:56:35,670 autoreload 14645 140142066329408 Watching for file changes with StatReloader
INFO 2022-04-19 07:57:22,805 autoreload 14645 140142066329408 /home/tracy/tracy_git_test/meiduo_mall/meiduo_mall/settings.py changed, reloading.
INFO 2022-04-19 07:57:24,589 autoreload 14714 140641430021952 Watching for file changes with StatReloader
INFO 2022-04-19 07:58:37,992 autoreload 14885 140478557501248 Watching for file changes with StatReloader
INFO 2022-04-19 08:00:51,595 autoreload 14885 140478557501248 /home/tracy/tracy_git_test/meiduo_mall/meiduo_mall/urls.py changed, reloading.
INFO 2022-04-19 08:00:53,408 autoreload 15013 140617923585856 Watching for file changes with StatReloader
INFO 2022-04-19 08:01:26,513 autoreload 15013 140617923585856 /home/tracy/tracy_git_test/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2022-04-19 08:01:28,333 autoreload 15101 140614259377984 Watching for file changes with StatReloader
WARNING 2022-04-19 08:02:13,219 log 15101 140613806716672 Not Found: /
WARNING 2022-04-19 08:02:13,221 basehttp 15101 140613806716672 "GET / HTTP/1.1" 404 2756
WARNING 2022-04-19 08:02:13,634 log 15101 140613806716672 Not Found: /favicon.ico
WARNING 2022-04-19 08:02:13,635 basehttp 15101 140613806716672 "GET /favicon.ico HTTP/1.1" 404 2807
ERROR 2022-04-19 08:03:21,695 log 15101 140613806716672 Internal Server Error: /image/a11212f8-e1e4-4eb8-8cb6-51731b03e953/count/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/verifications/views.py", line 13, in get
    text,image = Captcha.generate_captcha();
TypeError: generate_captcha() missing 1 required positional argument: 'self'
ERROR 2022-04-19 08:03:21,701 basehttp 15101 140613806716672 "GET /image/a11212f8-e1e4-4eb8-8cb6-51731b03e953/count/ HTTP/1.1" 500 77351
INFO 2022-04-19 08:06:45,072 autoreload 15101 140614259377984 /home/tracy/tracy_git_test/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2022-04-19 08:06:47,276 autoreload 15368 140703041500992 Watching for file changes with StatReloader
INFO 2022-04-19 08:06:54,746 basehttp 15368 140702591743744 "GET /image/a11212f8-e1e4-4eb8-8cb6-51731b03e953/count/ HTTP/1.1" 200 3334
INFO 2022-04-19 08:07:07,177 basehttp 15368 140702591743744 "GET /image/a11212f8-e1e4-4eb8-8cb6-51731b03e953/count/ HTTP/1.1" 200 3158
INFO 2022-04-19 08:07:09,267 basehttp 15368 140702591743744 "GET /image/a11212f8-e1e4-4eb8-8cb6-51731b03e953/count/ HTTP/1.1" 200 3389
INFO 2022-04-19 08:10:12,158 autoreload 15368 140703041500992 /home/tracy/tracy_git_test/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2022-04-19 08:10:15,505 autoreload 15612 140335350863680 Watching for file changes with StatReloader
INFO 2022-04-20 05:46:03,853 autoreload 14577 139666048440128 Watching for file changes with StatReloader
INFO 2022-04-20 05:46:37,521 autoreload 14716 139784608016192 Watching for file changes with StatReloader
WARNING 2022-04-20 05:47:36,475 log 14716 139784297207552 Not Found: /username/abc/count/
WARNING 2022-04-20 05:47:36,483 basehttp 14716 139784297207552 "GET /username/abc/count/ HTTP/1.1" 404 2831
INFO 2022-04-20 05:48:37,561 basehttp 14716 139784297207552 "GET /username/abcdefg/count/ HTTP/1.1" 200 39
INFO 2022-04-20 05:52:31,812 autoreload 14716 139784608016192 /home/tracy/tracy_git_test/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2022-04-20 05:52:34,795 autoreload 15202 140577539450688 Watching for file changes with StatReloader
INFO 2022-04-20 06:02:49,628 autoreload 15202 140577539450688 /home/tracy/tracy_git_test/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2022-04-20 06:02:52,250 autoreload 15349 140452617774912 Watching for file changes with StatReloader
INFO 2022-04-20 06:20:20,215 autoreload 15702 140252703250240 Watching for file changes with StatReloader
WARNING 2022-04-20 06:21:25,722 log 15702 140252258244352 Not Found: /
WARNING 2022-04-20 06:21:25,726 basehttp 15702 140252258244352 "GET / HTTP/1.1" 404 2929
WARNING 2022-04-20 06:21:26,410 log 15702 140252258244352 Not Found: /favicon.ico
WARNING 2022-04-20 06:21:26,411 basehttp 15702 140252258244352 "GET /favicon.ico HTTP/1.1" 404 2980
INFO 2022-04-20 06:21:51,113 basehttp 15702 140252258244352 "GET /image/12345/count/ HTTP/1.1" 200 2929
INFO 2022-04-20 06:23:50,550 basehttp 15702 140252258244352 "GET /sms/13812341234/?image_code=7zy4&image_code_id=12345/ HTTP/1.1" 200 69
INFO 2022-04-20 06:24:04,548 basehttp 15702 140252249851648 "GET /image/12345/count/ HTTP/1.1" 200 3244
INFO 2022-04-20 06:24:18,276 basehttp 15702 140252258244352 "GET /sms/13812341234/?image_code=hwwm&image_code_id=12345/ HTTP/1.1" 200 69
INFO 2022-04-20 06:28:47,965 autoreload 16404 140313281664832 Watching for file changes with StatReloader
INFO 2022-04-20 06:29:05,904 basehttp 16404 140312970856192 "GET /image/12345/count/ HTTP/1.1" 200 2963
INFO 2022-04-20 06:30:58,574 autoreload 16638 140085747926848 Watching for file changes with StatReloader
INFO 2022-04-20 06:31:04,213 basehttp 16638 140085302896384 "GET /image/12345/count/ HTTP/1.1" 200 3180
INFO 2022-04-20 06:31:18,907 basehttp 16638 140085294503680 "GET /sms/13812341234/?image_code=pduz&image_code_id=12345 HTTP/1.1" 200 31
INFO 2022-04-20 07:00:14,298 autoreload 17127 140684049356608 Watching for file changes with StatReloader
INFO 2022-04-20 07:00:22,208 basehttp 17127 140683599935232 "GET /image/12345/count/ HTTP/1.1" 200 3188
INFO 2022-04-20 07:00:38,132 basehttp 17127 140683591542528 "GET /sms/13812341234/?image_code=nk6r&image_code_id=12345 HTTP/1.1" 200 31
INFO 2022-04-20 07:00:40,748 basehttp 17127 140683591542528 "GET /sms/13812341234/?image_code=nk6r&image_code_id=12345 HTTP/1.1" 200 57
INFO 2022-04-20 07:01:19,059 basehttp 17127 140683591542528 "GET /sms/13812341234/?image_code=nk6r&image_code_id=12345 HTTP/1.1" 200 57
INFO 2022-04-20 07:01:24,830 basehttp 17127 140683591542528 "GET /sms/13812341234/?image_code=nk6r&image_code_id=12345 HTTP/1.1" 200 57
INFO 2022-04-20 07:01:42,666 basehttp 17127 140683591542528 "GET /sms/13812341234/?image_code=nk6r&image_code_id=12345 HTTP/1.1" 200 31
INFO 2022-04-20 07:14:44,055 autoreload 17601 140545999525696 Watching for file changes with StatReloader
INFO 2022-04-20 07:14:48,288 basehttp 17601 140545487271680 "GET /image/12345/count/ HTTP/1.1" 200 3435
INFO 2022-04-20 07:14:59,368 basehttp 17601 140545478878976 "GET /sms/13812341234/?image_code=dqyp&image_code_id=12345 HTTP/1.1" 200 31
INFO 2022-04-21 07:09:58,050 autoreload 6712 140587848652608 Watching for file changes with StatReloader
INFO 2022-04-21 07:14:11,109 autoreload 6712 140587848652608 /home/tracy/tracy_git_test/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2022-04-21 07:14:11,745 autoreload 6987 140226228377408 Watching for file changes with StatReloader
INFO 2022-04-21 07:14:34,217 autoreload 7001 139823205881664 Watching for file changes with StatReloader
WARNING 2022-04-21 07:15:00,947 log 7001 139823062972160 Not Found: /
WARNING 2022-04-21 07:15:00,947 basehttp 7001 139823062972160 "GET / HTTP/1.1" 404 2929
INFO 2022-04-21 07:15:37,956 basehttp 7001 139823062972160 "GET /image/12345/count/ HTTP/1.1" 200 3092
INFO 2022-04-21 07:15:54,100 basehttp 7001 139823054579456 "GET /sms/13812341234/?image_code=fjya&image_code_id=12345 HTTP/1.1" 200 31
INFO 2022-04-21 07:17:14,372 autoreload 7001 139823205881664 /home/tracy/tracy_git_test/meiduo_mall/celery_tasks/sms/tasks.py changed, reloading.
INFO 2022-04-21 07:17:15,292 autoreload 7321 140180488230720 Watching for file changes with StatReloader
INFO 2022-04-21 07:17:22,622 basehttp 7321 140180347463424 "GET /image/12345/count/ HTTP/1.1" 200 3039
INFO 2022-04-21 07:17:37,262 basehttp 7321 140180338808576 "GET /sms/13812341234/?image_code=37nj&image_code_id=12345 HTTP/1.1" 200 31
INFO 2022-04-21 07:53:05,504 autoreload 3791 140597185537856 Watching for file changes with StatReloader
ERROR 2022-04-21 07:54:58,682 log 3791 140596740556544 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: as_view() takes 1 positional argument but 2 were given
ERROR 2022-04-21 07:54:58,685 basehttp 3791 140596740556544 "POST /authorizations/ HTTP/1.1" 500 62866
INFO 2022-04-21 07:58:52,247 autoreload 3791 140597185537856 /home/tracy/tracy_git_test/meiduo_mall/apps/user/urls.py changed, reloading.
INFO 2022-04-21 07:58:54,628 autoreload 4223 140434999752512 Watching for file changes with StatReloader
INFO 2022-04-21 07:58:59,397 basehttp 4223 140434484279040 "POST /authorizations/ HTTP/1.1" 200 27
INFO 2022-04-21 07:59:11,820 basehttp 4223 140434484279040 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:06:58,805 autoreload 4223 140434999752512 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:07:00,559 autoreload 4409 140324137613120 Watching for file changes with StatReloader
INFO 2022-04-21 08:07:32,069 basehttp 4409 140323625367296 "POST /authorizations/ HTTP/1.1" 200 27
INFO 2022-04-21 08:11:20,486 autoreload 4409 140324137613120 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:11:22,246 autoreload 4544 140372208981824 Watching for file changes with StatReloader
INFO 2022-04-21 08:11:46,877 autoreload 4544 140372208981824 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:11:48,686 autoreload 4619 140452892706624 Watching for file changes with StatReloader
INFO 2022-04-21 08:13:12,331 autoreload 4619 140452892706624 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:13:14,407 autoreload 4717 139622065022784 Watching for file changes with StatReloader
INFO 2022-04-21 08:17:26,919 basehttp 4717 139621754205952 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:17:35,328 basehttp 4717 139621754205952 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:17:40,053 basehttp 4717 139621754205952 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:17:51,481 basehttp 4717 139621754205952 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:18:00,322 basehttp 4717 139621754205952 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:19:02,799 basehttp 4717 139621754205952 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:19:05,864 basehttp 4717 139621754205952 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:19:08,564 basehttp 4717 139621754205952 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:19:11,411 basehttp 4717 139621754205952 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:22:02,163 autoreload 4717 139622065022784 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:22:03,938 autoreload 5085 139722301323072 Watching for file changes with StatReloader
INFO 2022-04-21 08:27:44,474 autoreload 5085 139722301323072 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:27:46,386 autoreload 5202 140559895484224 Watching for file changes with StatReloader
ERROR 2022-04-21 08:28:02,451 log 5202 140559381427968 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 91, in post
    user = User.objects.get(username)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 482, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1466, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1496, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1339, in build_filter
    arg, value = filter_expr
ValueError: too many values to unpack (expected 2)
ERROR 2022-04-21 08:28:02,455 basehttp 5202 140559381427968 "POST /authorizations/ HTTP/1.1" 500 113132
INFO 2022-04-21 08:29:09,252 autoreload 5202 140559895484224 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:29:10,997 autoreload 5347 140025252493120 Watching for file changes with StatReloader
ERROR 2022-04-21 08:29:14,727 log 5347 140024941725440 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 91, in post
    user = User.objects.get(username)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 482, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1466, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1496, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1339, in build_filter
    arg, value = filter_expr
ValueError: too many values to unpack (expected 2)
ERROR 2022-04-21 08:29:14,731 basehttp 5347 140024941725440 "POST /authorizations/ HTTP/1.1" 500 113134
INFO 2022-04-21 08:30:32,784 autoreload 5347 140025252493120 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:30:34,649 autoreload 5483 140536523036480 Watching for file changes with StatReloader
ERROR 2022-04-21 08:30:39,323 log 5483 140536077989632 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 99, in post
    if user is None:
NameError: name 'user' is not defined
ERROR 2022-04-21 08:30:39,327 basehttp 5483 140536077989632 "POST /authorizations/ HTTP/1.1" 500 76495
ERROR 2022-04-21 08:30:42,243 log 5483 140536077989632 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 99, in post
    if user is None:
NameError: name 'user' is not defined
ERROR 2022-04-21 08:30:42,245 basehttp 5483 140536077989632 "POST /authorizations/ HTTP/1.1" 500 76495
INFO 2022-04-21 08:30:53,309 autoreload 5483 140536523036480 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:30:55,054 autoreload 5600 140051130144576 Watching for file changes with StatReloader
INFO 2022-04-21 08:32:18,624 autoreload 5600 140051130144576 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:32:20,420 autoreload 5699 140372126684992 Watching for file changes with StatReloader
ERROR 2022-04-21 08:32:31,091 log 5699 140371677935360 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 91, in post
    user = User.objects.get(username)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 482, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1466, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1496, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1339, in build_filter
    arg, value = filter_expr
ValueError: too many values to unpack (expected 2)
ERROR 2022-04-21 08:32:31,095 basehttp 5699 140371677935360 "POST /authorizations/ HTTP/1.1" 500 113134
INFO 2022-04-21 08:32:36,883 autoreload 5699 140372126684992 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:32:38,796 autoreload 5827 140182728378176 Watching for file changes with StatReloader
ERROR 2022-04-21 08:32:55,660 log 5827 140182283396864 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 109, in post
    response.set_cookie('username',username)
AttributeError: module 'django.http.response' has no attribute 'set_cookie'
ERROR 2022-04-21 08:32:55,663 basehttp 5827 140182283396864 "POST /authorizations/ HTTP/1.1" 500 76595
INFO 2022-04-21 08:33:30,525 autoreload 5827 140182728378176 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:33:32,452 autoreload 5952 140268049205056 Watching for file changes with StatReloader
INFO 2022-04-21 08:33:35,691 basehttp 5952 140267738433280 "POST /authorizations/ HTTP/1.1" 200 27
INFO 2022-04-21 08:33:44,813 autoreload 5952 140268049205056 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:33:46,587 autoreload 6061 140429332113216 Watching for file changes with StatReloader
ERROR 2022-04-21 08:33:49,703 log 6061 140428887131904 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 91, in post
    user = User.objects.get(username)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 482, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1466, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1496, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1339, in build_filter
    arg, value = filter_expr
ValueError: too many values to unpack (expected 2)
ERROR 2022-04-21 08:33:49,707 basehttp 6061 140428887131904 "POST /authorizations/ HTTP/1.1" 500 113134
INFO 2022-04-21 08:35:36,326 autoreload 6061 140429332113216 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:35:37,943 autoreload 6152 139882470672192 Watching for file changes with StatReloader
INFO 2022-04-21 08:35:41,872 autoreload 6152 139882470672192 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:35:43,554 autoreload 6219 140592759568192 Watching for file changes with StatReloader
ERROR 2022-04-21 08:35:47,779 log 6219 140592314545920 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 92, in post
    user = User.objects.get(name='username')
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 482, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1466, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1496, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1342, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1156, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1640, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, mobiles, password, user_permissions, username
ERROR 2022-04-21 08:35:47,786 basehttp 6219 140592314545920 "POST /authorizations/ HTTP/1.1" 500 124923
INFO 2022-04-21 08:36:22,811 autoreload 6219 140592759568192 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:36:24,652 autoreload 6317 140160749426496 Watching for file changes with StatReloader
INFO 2022-04-21 08:36:28,733 basehttp 6317 140160438634240 "POST /authorizations/ HTTP/1.1" 200 27
INFO 2022-04-21 08:39:04,171 autoreload 6317 140160749426496 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:39:06,008 autoreload 6492 140668470208320 Watching for file changes with StatReloader
INFO 2022-04-21 08:39:23,328 autoreload 6492 140668470208320 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:39:25,023 autoreload 6566 139984646821696 Watching for file changes with StatReloader
ERROR 2022-04-21 08:39:28,254 log 6566 139984470271744 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 98, in post
    print(user.check_password())
TypeError: check_password() missing 1 required positional argument: 'raw_password'
ERROR 2022-04-21 08:39:28,257 basehttp 6566 139984470271744 "POST /authorizations/ HTTP/1.1" 500 76836
INFO 2022-04-21 08:39:52,893 autoreload 6566 139984646821696 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:39:54,566 autoreload 6658 140349286401856 Watching for file changes with StatReloader
INFO 2022-04-21 08:39:57,992 basehttp 6658 140348841346816 "POST /authorizations/ HTTP/1.1" 200 27
INFO 2022-04-21 08:45:04,560 autoreload 6658 140349286401856 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 08:45:06,471 autoreload 6804 140414285895488 Watching for file changes with StatReloader
INFO 2022-04-21 08:45:09,580 basehttp 6804 140413975131904 "POST /authorizations/ HTTP/1.1" 200 27
INFO 2022-04-21 08:49:57,693 autoreload 7043 140349248141120 Watching for file changes with StatReloader
INFO 2022-04-21 08:50:21,386 basehttp 7043 140349071570688 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:50:39,734 autoreload 7221 140494558455616 Watching for file changes with StatReloader
INFO 2022-04-21 08:54:11,580 basehttp 7221 140494113453824 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:54:18,826 basehttp 7221 140494113453824 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:54:25,174 basehttp 7221 140494113453824 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:54:38,951 basehttp 7221 140494113453824 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:55:25,032 basehttp 7221 140494113453824 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:55:31,842 basehttp 7221 140494113453824 "POST /authorizations/ HTTP/1.1" 200 69
INFO 2022-04-21 08:56:50,651 basehttp 7221 140494113453824 "POST /user/ HTTP/1.1" 200 27
WARNING 2022-04-21 08:57:50,849 base 7221 140494113453824 Method Not Allowed (GET): /authorizations/
WARNING 2022-04-21 08:57:50,850 log 7221 140494113453824 Method Not Allowed: /authorizations/
WARNING 2022-04-21 08:57:50,852 basehttp 7221 140494113453824 "GET /authorizations/ HTTP/1.1" 405 0
WARNING 2022-04-21 08:58:56,471 base 7221 140494113453824 Method Not Allowed (GET): /authorizations/
WARNING 2022-04-21 08:58:56,472 log 7221 140494113453824 Method Not Allowed: /authorizations/
WARNING 2022-04-21 08:58:56,474 basehttp 7221 140494113453824 "GET /authorizations/ HTTP/1.1" 405 0
INFO 2022-04-21 09:02:11,230 autoreload 7871 140482082895680 Watching for file changes with StatReloader
ERROR 2022-04-21 09:02:14,348 log 7871 140481637914368 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tracy/.virtualenvs/test_env/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py", line 110, in post
    response.set_cookie('username',username)
AttributeError: module 'django.http.response' has no attribute 'set_cookie'
ERROR 2022-04-21 09:02:14,354 basehttp 7871 140481637914368 "POST /authorizations/ HTTP/1.1" 500 77219
INFO 2022-04-21 09:04:12,839 autoreload 7871 140482082895680 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 09:04:14,785 autoreload 7959 140454829008704 Watching for file changes with StatReloader
INFO 2022-04-21 09:04:17,902 basehttp 7959 140454518220544 "POST /authorizations/ HTTP/1.1" 200 27
INFO 2022-04-21 09:05:33,316 autoreload 7959 140454829008704 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 09:05:35,074 autoreload 8076 140310296274752 Watching for file changes with StatReloader
INFO 2022-04-21 09:05:40,329 basehttp 8076 140309851289344 "POST /authorizations/ HTTP/1.1" 200 27
INFO 2022-04-21 09:05:57,752 autoreload 8076 140310296274752 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 09:05:59,579 autoreload 8189 139813066393408 Watching for file changes with StatReloader
INFO 2022-04-21 09:06:07,603 autoreload 8189 139813066393408 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-21 09:06:09,419 autoreload 8263 139900781946688 Watching for file changes with StatReloader
INFO 2022-04-24 06:01:52,585 autoreload 4765 140563527849792 Watching for file changes with StatReloader
INFO 2022-04-24 06:02:31,868 basehttp 4765 140563351295744 "POST /authorizations/ HTTP/1.1" 200 27
INFO 2022-04-24 06:03:42,182 basehttp 4765 140563351295744 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2022-04-24 06:04:57,281 autoreload 4765 140563527849792 /home/tracy/tracy_git_test/meiduo_mall/apps/user/views.py changed, reloading.
INFO 2022-04-24 06:04:59,165 autoreload 5137 139666738964288 Watching for file changes with StatReloader
